muniinfo = {
"RSA" : { "name" : "South Africa", "layer" : 0, "parent" : null },
"EC" : { "name" : "Eastern Cape", "layer" : 1, "parent" : "RSA" },
"FS" : { "name" : "Free State", "layer" : 1, "parent" : "RSA" },
"GT" : { "name" : "Gauteng", "layer" : 1, "parent" : "RSA" },
"KZ" : { "name" : "KwaZulu-Natal", "layer" : 1, "parent" : "RSA" },
"LP" : { "name" : "Limpopo", "layer" : 1, "parent" : "RSA" },
"MP" : { "name" : "Mpumalanga", "layer" : 1, "parent" : "RSA" },
"NC" : { "name" : "Northern Cape", "layer" : 1, "parent" : "RSA" },
"NW" : { "name" : "North West", "layer" : 1, "parent" : "RSA" },
"WC" : { "name" : "Western Cape", "layer" : 1, "parent" : "RSA" },
"CPT" : { "name" : "City of Cape Town Metropolitan Municipality", "layer" : 2, "parent" : "WC" },
"DC1" : { "name" : "West Coast District Municipality", "layer" : 2, "parent" : "WC" },
"DC10" : { "name" : "Cacadu District Municipality", "layer" : 2, "parent" : "EC" },
"DC12" : { "name" : "Amatole District Municipality", "layer" : 2, "parent" : "EC" },
"DC13" : { "name" : "Chris Hani District Municipality", "layer" : 2, "parent" : "EC" },
"DC14" : { "name" : "Ukhahlamba District Municipality", "layer" : 2, "parent" : "EC" },
"DC15" : { "name" : "O.R.Tambo District Municipality", "layer" : 2, "parent" : "EC" },
"DC16" : { "name" : "Xhariep District Municipality", "layer" : 2, "parent" : "FS" },
"DC17" : { "name" : "Motheo District Municipality", "layer" : 2, "parent" : "FS" },
"DC18" : { "name" : "Lejweleputswa District Municipality", "layer" : 2, "parent" : "FS" },
"DC19" : { "name" : "Thabo Mofutsanyane District Municipality", "layer" : 2, "parent" : "FS" },
"DC2" : { "name" : "Cape Winelands District Municipality", "layer" : 2, "parent" : "WC" },
"DC20" : { "name" : "Fezile Dabi District Municipality", "layer" : 2, "parent" : "FS" },
"DC21" : { "name" : "Ugu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC22" : { "name" : "UMgungundlovu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC23" : { "name" : "Uthukela District Municipality", "layer" : 2, "parent" : "KZ" },
"DC24" : { "name" : "Umzinyathi District Municipality", "layer" : 2, "parent" : "KZ" },
"DC25" : { "name" : "Amajuba District Municipality", "layer" : 2, "parent" : "KZ" },
"DC26" : { "name" : "Zululand District Municipality", "layer" : 2, "parent" : "KZ" },
"DC27" : { "name" : "Umkhanyakude District Municipality", "layer" : 2, "parent" : "KZ" },
"DC28" : { "name" : "Uthungulu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC29" : { "name" : "iLembe District Municipality", "layer" : 2, "parent" : "KZ" },
"DC3" : { "name" : "Overberg District Municipality", "layer" : 2, "parent" : "WC" },
"DC30" : { "name" : "Gert Sibande District Municipality", "layer" : 2, "parent" : "MP" },
"DC31" : { "name" : "Nkangala District Municipality", "layer" : 2, "parent" : "MP" },
"DC32" : { "name" : "Ehlanzeni District Municipality", "layer" : 2, "parent" : "MP" },
"DC33" : { "name" : "Mopani District Municipality", "layer" : 2, "parent" : "LP" },
"DC34" : { "name" : "Vhembe District Municipality", "layer" : 2, "parent" : "LP" },
"DC35" : { "name" : "Capricorn District Municipality", "layer" : 2, "parent" : "LP" },
"DC36" : { "name" : "Waterberg District Municipality", "layer" : 2, "parent" : "LP" },
"DC37" : { "name" : "Bojanala District Municipality", "layer" : 2, "parent" : "NW" },
"DC38" : { "name" : "Central District Municipality", "layer" : 2, "parent" : "NW" },
"DC39" : { "name" : "Bophirima District Municipality", "layer" : 2, "parent" : "NW" },
"DC4" : { "name" : "Eden District Municipality", "layer" : 2, "parent" : "WC" },
"DC40" : { "name" : "Southern District Municipality", "layer" : 2, "parent" : "NW" },
"DC42" : { "name" : "Sedibeng District Municipality", "layer" : 2, "parent" : "GT" },
"DC43" : { "name" : "Sisonke District Municipality", "layer" : 2, "parent" : "KZ" },
"DC44" : { "name" : "Alfred Nzo District Municipality", "layer" : 2, "parent" : "EC" },
"DC45" : { "name" : "Kgalagadi District Municipality", "layer" : 2, "parent" : "NC" },
"DC46" : { "name" : "Metsweding District Municipality", "layer" : 2, "parent" : "GT" },
"DC47" : { "name" : "Greater Sekhukhune District Municipality", "layer" : 2, "parent" : "LP" },
"DC48" : { "name" : "West Rand District Municipality", "layer" : 2, "parent" : "GT" },
"DC5" : { "name" : "Central Karoo District Municipality", "layer" : 2, "parent" : "WC" },
"DC6" : { "name" : "Namakwa District Municipality", "layer" : 2, "parent" : "NC" },
"DC7" : { "name" : "Pixley ka Seme District Municipality", "layer" : 2, "parent" : "NC" },
"DC8" : { "name" : "Siyanda District Municipality", "layer" : 2, "parent" : "NC" },
"DC9" : { "name" : "Frances Baard District Municipality", "layer" : 2, "parent" : "NC" },
"EKU" : { "name" : "Ekurhuleni Metropolitan Municipality", "layer" : 2, "parent" : "GT" },
"ETH" : { "name" : "eThekwini Metropolitan Municipality", "layer" : 2, "parent" : "KZ" },
"JHB" : { "name" : "City of Johannesburg Metropolitan Municipality", "layer" : 2, "parent" : "GT" },
"NMA" : { "name" : "Nelson Mandela Bay Metropolitan Municipality", "layer" : 2, "parent" : "EC" },
"TSH" : { "name" : "City of Tshwane Metropolitan Municipality", "layer" : 2, "parent" : "GT" },
"EC101" : { "name" : "Camdeboo Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC102" : { "name" : "Blue Crane Route Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC103" : { "name" : "Ikwezi Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC104" : { "name" : "Makana Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC105" : { "name" : "Ndlambe Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC106" : { "name" : "Sunday's River Valley Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC107" : { "name" : "Baviaans Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC108" : { "name" : "Kouga Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC109" : { "name" : "Kou-Kamma Local Municipality", "layer" : 3, "parent" : "DC10" },
"EC121" : { "name" : "Mbhashe Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC122" : { "name" : "Mnquma Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC123" : { "name" : "Great Kei Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC124" : { "name" : "Amahlathi Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC125" : { "name" : "Buffalo City Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC126" : { "name" : "Ngqushwa Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC127" : { "name" : "Nkonkobe Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC128" : { "name" : "Nxuba Local Municipality", "layer" : 3, "parent" : "DC12" },
"EC131" : { "name" : "Inxuba Yethemba Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC132" : { "name" : "Tsolwana Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC133" : { "name" : "Inkwanca Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC134" : { "name" : "Lukanji Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC135" : { "name" : "Intsika Yethu Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC136" : { "name" : "Emalahleni Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC137" : { "name" : "Engcobo Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC138" : { "name" : "Sakhisizwe Local Municipality", "layer" : 3, "parent" : "DC13" },
"EC141" : { "name" : "Elundini Local Municipality", "layer" : 3, "parent" : "DC14" },
"EC142" : { "name" : "Senqu Local Municipality", "layer" : 3, "parent" : "DC14" },
"EC143" : { "name" : "Maletswai Local Municipality", "layer" : 3, "parent" : "DC14" },
"EC144" : { "name" : "Gariep Local Municipality", "layer" : 3, "parent" : "DC14" },
"EC151" : { "name" : "Mbizana Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC152" : { "name" : "Ntabankulu Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC153" : { "name" : "Qaukeni Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC154" : { "name" : "Port St Johns Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC155" : { "name" : "Nyandeni Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC156" : { "name" : "Mhlontlo Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC157" : { "name" : "King Sabata Dalindyebo Local Municipality", "layer" : 3, "parent" : "DC15" },
"EC441" : { "name" : "Matatiele Local Municipality", "layer" : 3, "parent" : "DC44" },
"EC442" : { "name" : "Umzimvubu Local Municipality", "layer" : 3, "parent" : "DC44" },
"ECDMA10" : { "name" : "Cacadu District Management Area", "layer" : 3, "parent" : "DC10" },
"ECDMA13" : { "name" : "Chris Hani District Management Area", "layer" : 3, "parent" : "DC13" },
"FS161" : { "name" : "Letsemeng Local Municipality", "layer" : 3, "parent" : "DC16" },
"FS162" : { "name" : "Kopanong Local Municipality", "layer" : 3, "parent" : "DC16" },
"FS163" : { "name" : "Mohokare Local Municipality", "layer" : 3, "parent" : "DC16" },
"FS171" : { "name" : "Naledi Local Municipality", "layer" : 3, "parent" : "DC17" },
"FS172" : { "name" : "Mangaung Local Municipality", "layer" : 3, "parent" : "DC17" },
"FS173" : { "name" : "Mantsopa Local Municipality", "layer" : 3, "parent" : "DC17" },
"FS181" : { "name" : "Masilonyana Local Municipality", "layer" : 3, "parent" : "DC18" },
"FS182" : { "name" : "Tokologo Local Municipality", "layer" : 3, "parent" : "DC18" },
"FS183" : { "name" : "Tswelopele Local Municipality", "layer" : 3, "parent" : "DC18" },
"FS184" : { "name" : "Matjhabeng Local Municipality", "layer" : 3, "parent" : "DC18" },
"FS185" : { "name" : "Nala Local Municipality", "layer" : 3, "parent" : "DC18" },
"FS191" : { "name" : "Setsoto Local Municipality", "layer" : 3, "parent" : "DC19" },
"FS192" : { "name" : "Dihlabeng Local Municipality", "layer" : 3, "parent" : "DC19" },
"FS193" : { "name" : "Nketoana Local Municipality", "layer" : 3, "parent" : "DC19" },
"FS194" : { "name" : "Maluti a Phofung Local Municipality", "layer" : 3, "parent" : "DC19" },
"FS195" : { "name" : "Phumelela Local Municipality", "layer" : 3, "parent" : "DC19" },
"FS201" : { "name" : "Moqhaka Local Municipality", "layer" : 3, "parent" : "DC20" },
"FS203" : { "name" : "Ngwathe Local Municipality", "layer" : 3, "parent" : "DC20" },
"FS204" : { "name" : "Metsimaholo Local Municipality", "layer" : 3, "parent" : "DC20" },
"FS205" : { "name" : "Mafube Local Municipality", "layer" : 3, "parent" : "DC20" },
"FSDMA19" : { "name" : "Thabo Mofutsanyane District Management Area", "layer" : 3, "parent" : "DC19" },
"GT421" : { "name" : "Emfuleni Local Municipality", "layer" : 3, "parent" : "DC42" },
"GT422" : { "name" : "Midvaal Local Municipality", "layer" : 3, "parent" : "DC42" },
"GT423" : { "name" : "Lesedi Local Municipality", "layer" : 3, "parent" : "DC42" },
"GT461" : { "name" : "Nokeng tsa Taemane Local Municipality", "layer" : 3, "parent" : "DC46" },
"GT462" : { "name" : "Kungwini Local Municipality", "layer" : 3, "parent" : "DC46" },
"GT481" : { "name" : "Mogale City Local Municipality", "layer" : 3, "parent" : "DC48" },
"GT482" : { "name" : "Randfontein Local Municipality", "layer" : 3, "parent" : "DC48" },
"GT483" : { "name" : "Westonaria Local Municipality", "layer" : 3, "parent" : "DC48" },
"GT484" : { "name" : "Merafong City Local Municipality", "layer" : 3, "parent" : "DC48" },
"GTDMA48" : { "name" : "West Rand District Management Area", "layer" : 3, "parent" : "DC48" },
"KZN211" : { "name" : "Vulamehlo Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN212" : { "name" : "Umdoni Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN213" : { "name" : "Umzumbe Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN214" : { "name" : "UMuziwabantu Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN215" : { "name" : "Ezingoleni Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN216" : { "name" : "Hibiscus Coast Local Municipality", "layer" : 3, "parent" : "DC21" },
"KZN221" : { "name" : "uMshwathi Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN222" : { "name" : "uMngeni Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN223" : { "name" : "Mooi Mpofana Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN224" : { "name" : "Impendle Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN225" : { "name" : "The Msunduzi Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN226" : { "name" : "Mkhambathini Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN227" : { "name" : "Richmond Local Municipality", "layer" : 3, "parent" : "DC22" },
"KZN232" : { "name" : "Emnambithi/Ladysmith Local Municipality", "layer" : 3, "parent" : "DC23" },
"KZN233" : { "name" : "Indaka Local Municipality", "layer" : 3, "parent" : "DC23" },
"KZN234" : { "name" : "Umtshezi Local Municipality", "layer" : 3, "parent" : "DC23" },
"KZN235" : { "name" : "Okhahlamba Local Municipality", "layer" : 3, "parent" : "DC23" },
"KZN236" : { "name" : "Imbabazane Local Municipality", "layer" : 3, "parent" : "DC23" },
"KZN241" : { "name" : "Endumeni Local Municipality", "layer" : 3, "parent" : "DC24" },
"KZN242" : { "name" : "Nqutu Local Municipality", "layer" : 3, "parent" : "DC24" },
"KZN244" : { "name" : "Msinga Local Municipality", "layer" : 3, "parent" : "DC24" },
"KZN245" : { "name" : "Umvoti Local Municipality", "layer" : 3, "parent" : "DC24" },
"KZN252" : { "name" : "Newcastle Local Municipality", "layer" : 3, "parent" : "DC25" },
"KZN253" : { "name" : "Utrecht Local Municipality", "layer" : 3, "parent" : "DC25" },
"KZN254" : { "name" : "Dannhauser Local Municipality", "layer" : 3, "parent" : "DC25" },
"KZN261" : { "name" : "eDumbe Local Municipality", "layer" : 3, "parent" : "DC26" },
"KZN262" : { "name" : "UPhongolo Local Municipality", "layer" : 3, "parent" : "DC26" },
"KZN263" : { "name" : "Abaqulusi Local Municipality", "layer" : 3, "parent" : "DC26" },
"KZN265" : { "name" : "Nongoma Local Municipality", "layer" : 3, "parent" : "DC26" },
"KZN266" : { "name" : "Ulundi Local Municipality", "layer" : 3, "parent" : "DC26" },
"KZN271" : { "name" : "Umhlabuyalingana Local Municipality", "layer" : 3, "parent" : "DC27" },
"KZN272" : { "name" : "Jozini Local Municipality", "layer" : 3, "parent" : "DC27" },
"KZN273" : { "name" : "The Big 5 False Bay Local Municipality", "layer" : 3, "parent" : "DC27" },
"KZN274" : { "name" : "Hlabisa Local Municipality", "layer" : 3, "parent" : "DC27" },
"KZN275" : { "name" : "Mtubatuba Local Municipality", "layer" : 3, "parent" : "DC27" },
"KZN281" : { "name" : "Mbonambi Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN282" : { "name" : "uMhlathuze Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN283" : { "name" : "Ntambanana Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN284" : { "name" : "uMlalazi Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN285" : { "name" : "Mthonjaneni Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN286" : { "name" : "Nkandla Local Municipality", "layer" : 3, "parent" : "DC28" },
"KZN291" : { "name" : "eNdondakusuka Local Municipality", "layer" : 3, "parent" : "DC29" },
"KZN292" : { "name" : "KwaDukuza Local Municipality", "layer" : 3, "parent" : "DC29" },
"KZN293" : { "name" : "Ndwedwe Local Municipality", "layer" : 3, "parent" : "DC29" },
"KZN294" : { "name" : "Maphumulo Local Municipality", "layer" : 3, "parent" : "DC29" },
"KZN431" : { "name" : "Ingwe Local Municipality", "layer" : 3, "parent" : "DC43" },
"KZN432" : { "name" : "Kwa Sani Local Municipality", "layer" : 3, "parent" : "DC43" },
"KZN433" : { "name" : "Greater Kokstad Local Municipality", "layer" : 3, "parent" : "DC43" },
"KZN434" : { "name" : "Ubuhlebezwe Local Municipality", "layer" : 3, "parent" : "DC43" },
"KZN435" : { "name" : "Umzimkhulu Local Municipality", "layer" : 3, "parent" : "DC43" },
"KZNDMA22" : { "name" : "UMgungundlovu District Management Area", "layer" : 3, "parent" : "DC22" },
"KZNDMA23" : { "name" : "Uthukela District Management Area", "layer" : 3, "parent" : "DC23" },
"KZNDMA27" : { "name" : "Umkhanyakude District Management Area", "layer" : 3, "parent" : "DC27" },
"KZNDMA43" : { "name" : "Sisonke District Management Area", "layer" : 3, "parent" : "DC43" },
"LIM331" : { "name" : "Greater Giyani Local Municipality", "layer" : 3, "parent" : "DC33" },
"LIM332" : { "name" : "Greater Letaba Local Municipality", "layer" : 3, "parent" : "DC33" },
"LIM333" : { "name" : "Greater Tzaneen Local Municipality", "layer" : 3, "parent" : "DC33" },
"LIM334" : { "name" : "Ba-Phalaborwa Local Municipality", "layer" : 3, "parent" : "DC33" },
"LIM335" : { "name" : "Maruleng Local Municipality", "layer" : 3, "parent" : "DC33" },
"LIM341" : { "name" : "Musina Local Municipality", "layer" : 3, "parent" : "DC34" },
"LIM342" : { "name" : "Mutale Local Municipality", "layer" : 3, "parent" : "DC34" },
"LIM343" : { "name" : "Thulamela Local Municipality", "layer" : 3, "parent" : "DC34" },
"LIM344" : { "name" : "Makhado Local Municipality", "layer" : 3, "parent" : "DC34" },
"LIM351" : { "name" : "Blouberg Local Municipality", "layer" : 3, "parent" : "DC35" },
"LIM352" : { "name" : "Aganang Local Municipality", "layer" : 3, "parent" : "DC35" },
"LIM353" : { "name" : "Molemole Local Municipality", "layer" : 3, "parent" : "DC35" },
"LIM354" : { "name" : "Polokwane Local Municipality", "layer" : 3, "parent" : "DC35" },
"LIM355" : { "name" : "Lepele-Nkumpi Local Municipality", "layer" : 3, "parent" : "DC35" },
"LIM361" : { "name" : "Thabazimbi Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM362" : { "name" : "Lephalale Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM364" : { "name" : "Mookgopong Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM365" : { "name" : "Modimolle Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM366" : { "name" : "Bela-Bela Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM367" : { "name" : "Mogalakwena Local Municipality", "layer" : 3, "parent" : "DC36" },
"LIM471" : { "name" : "Greater Marble Hall Local Municipality", "layer" : 3, "parent" : "DC47" },
"LIM472" : { "name" : "Elias Motsoaledi Local Municipality", "layer" : 3, "parent" : "DC47" },
"LIM473" : { "name" : "Makhuduthamaga Local Municipality", "layer" : 3, "parent" : "DC47" },
"LIM474" : { "name" : "Fetakgomo Local Municipality", "layer" : 3, "parent" : "DC47" },
"LIM475" : { "name" : "Greater Tubatse Local Municipality", "layer" : 3, "parent" : "DC47" },
"LIMDMA33" : { "name" : "Mopani District Management Area", "layer" : 3, "parent" : "DC33" },
"MP301" : { "name" : "Albert Luthuli Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP302" : { "name" : "Msukaligwa Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP303" : { "name" : "Mkhondo Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP304" : { "name" : "Seme Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP305" : { "name" : "Lekwa Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP306" : { "name" : "Dipaleseng Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP307" : { "name" : "Govan Mbeki Local Municipality", "layer" : 3, "parent" : "DC30" },
"MP311" : { "name" : "Delmas Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP312" : { "name" : "Emalahleni Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP313" : { "name" : "Steve Tshwete Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP314" : { "name" : "Highlands Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP315" : { "name" : "Thembisile Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP316" : { "name" : "Dr JS Moroka Local Municipality", "layer" : 3, "parent" : "DC31" },
"MP321" : { "name" : "Thaba Chweu Local Municipality", "layer" : 3, "parent" : "DC32" },
"MP322" : { "name" : "Mbombela Local Municipality", "layer" : 3, "parent" : "DC32" },
"MP323" : { "name" : "Umjindi Local Municipality", "layer" : 3, "parent" : "DC32" },
"MP324" : { "name" : "Nkomazi Local Municipality", "layer" : 3, "parent" : "DC32" },
"MP325" : { "name" : "Bushbuckridge Local Municipality", "layer" : 3, "parent" : "DC32" },
"MPDMA32" : { "name" : "Ehlanzeni District Management Area", "layer" : 3, "parent" : "DC32" },
"NC061" : { "name" : "Richtersveld Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC062" : { "name" : "Nama Khoi Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC064" : { "name" : "Kamiesberg Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC065" : { "name" : "Hantam Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC066" : { "name" : "Karoo Hoogland Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC067" : { "name" : "Khâi-Ma Local Municipality", "layer" : 3, "parent" : "DC6" },
"NC071" : { "name" : "Ubuntu Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC072" : { "name" : "Umsobomvu Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC073" : { "name" : "Emthanjeni Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC074" : { "name" : "Kareeberg Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC075" : { "name" : "Renosterberg Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC076" : { "name" : "Thembelihle Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC077" : { "name" : "Siyathemba Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC078" : { "name" : "Siyancuma Local Municipality", "layer" : 3, "parent" : "DC7" },
"NC081" : { "name" : "Mier Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC082" : { "name" : "Kai !Garib Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC083" : { "name" : "//Khara Hais Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC084" : { "name" : "!Kheis Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC085" : { "name" : "Tsantsabane Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC086" : { "name" : "Kgatelopele Local Municipality", "layer" : 3, "parent" : "DC8" },
"NC091" : { "name" : "Sol Plaatjie Local Municipality", "layer" : 3, "parent" : "DC9" },
"NC092" : { "name" : "Dikgatlong Local Municipality", "layer" : 3, "parent" : "DC9" },
"NC093" : { "name" : "Magareng Local Municipality", "layer" : 3, "parent" : "DC9" },
"NC094" : { "name" : "Phokwane Local Municipality", "layer" : 3, "parent" : "DC9" },
"NC451" : { "name" : "Moshaweng Local Municipality", "layer" : 3, "parent" : "DC45" },
"NC452" : { "name" : "Ga-Segonyana Local Municipality", "layer" : 3, "parent" : "DC45" },
"NC453" : { "name" : "Gamagara Local Municipality", "layer" : 3, "parent" : "DC45" },
"NCDMA06" : { "name" : "Namakwa District Management Area", "layer" : 3, "parent" : "DC6" },
"NCDMA07" : { "name" : "Pixley ka Seme District Management Area", "layer" : 3, "parent" : "DC7" },
"NCDMA08" : { "name" : "Siyanda District Management Area", "layer" : 3, "parent" : "DC8" },
"NCDMA09" : { "name" : "Frances Baard District Management Area", "layer" : 3, "parent" : "DC9" },
"NCDMA45" : { "name" : "Kgalagadi District Management Area", "layer" : 3, "parent" : "DC45" },
"NW371" : { "name" : "Moretele Local Municipality", "layer" : 3, "parent" : "DC37" },
"NW372" : { "name" : "Madibeng Local Municipality", "layer" : 3, "parent" : "DC37" },
"NW373" : { "name" : "Rustenburg Local Municipality", "layer" : 3, "parent" : "DC37" },
"NW374" : { "name" : "Kgetlengrivier Local Municipality", "layer" : 3, "parent" : "DC37" },
"NW375" : { "name" : "Moses Kotane Local Municipality", "layer" : 3, "parent" : "DC37" },
"NW381" : { "name" : "Ratlou Local Municipality", "layer" : 3, "parent" : "DC38" },
"NW382" : { "name" : "Tswaing Local Municipality", "layer" : 3, "parent" : "DC38" },
"NW383" : { "name" : "Mafikeng Local Municipality", "layer" : 3, "parent" : "DC38" },
"NW384" : { "name" : "Ditsobotla Local Municipality", "layer" : 3, "parent" : "DC38" },
"NW385" : { "name" : "Ramotshere Moiloa Local Municipality", "layer" : 3, "parent" : "DC38" },
"NW391" : { "name" : "Kagisano Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW392" : { "name" : "Naledi Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW393" : { "name" : "Mamusa Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW394" : { "name" : "Greater Taung Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW395" : { "name" : "Molopo Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW396" : { "name" : "Lekwa-Teemane Local Municipality", "layer" : 3, "parent" : "DC39" },
"NW401" : { "name" : "Ventersdorp Local Municipality", "layer" : 3, "parent" : "DC40" },
"NW402" : { "name" : "Potchefstroom Local Municipality", "layer" : 3, "parent" : "DC40" },
"NW403" : { "name" : "Matlosana Local Municipality", "layer" : 3, "parent" : "DC40" },
"NW404" : { "name" : "Maquassi Hills Local Municipality", "layer" : 3, "parent" : "DC40" },
"WC011" : { "name" : "Matzikama Local Municipality", "layer" : 3, "parent" : "DC1" },
"WC012" : { "name" : "Cederberg Local Municipality", "layer" : 3, "parent" : "DC1" },
"WC013" : { "name" : "Bergrivier Local Municipality", "layer" : 3, "parent" : "DC1" },
"WC014" : { "name" : "Saldanha Bay Local Municipality", "layer" : 3, "parent" : "DC1" },
"WC015" : { "name" : "Swartland Local Municipality", "layer" : 3, "parent" : "DC1" },
"WC022" : { "name" : "Witzenberg Local Municipality", "layer" : 3, "parent" : "DC2" },
"WC023" : { "name" : "Drakenstein Local Municipality", "layer" : 3, "parent" : "DC2" },
"WC024" : { "name" : "Stellenbosch Local Municipality", "layer" : 3, "parent" : "DC2" },
"WC025" : { "name" : "Breede Valley Local Municipality", "layer" : 3, "parent" : "DC2" },
"WC026" : { "name" : "Breede River/Winelands Local Municipality", "layer" : 3, "parent" : "DC2" },
"WC031" : { "name" : "Theewaterskloof Local Municipality", "layer" : 3, "parent" : "DC3" },
"WC032" : { "name" : "Overstrand Local Municipality", "layer" : 3, "parent" : "DC3" },
"WC033" : { "name" : "Cape Agulhas Local Municipality", "layer" : 3, "parent" : "DC3" },
"WC034" : { "name" : "Swellendam Local Municipality", "layer" : 3, "parent" : "DC3" },
"WC041" : { "name" : "Kannaland Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC042" : { "name" : "Hessequa Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC043" : { "name" : "Mossel Bay Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC044" : { "name" : "George Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC045" : { "name" : "Oudtshoorn Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC047" : { "name" : "Plettenberg Bay Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC048" : { "name" : "Knysna Local Municipality", "layer" : 3, "parent" : "DC4" },
"WC051" : { "name" : "Laingsburg Local Municipality", "layer" : 3, "parent" : "DC5" },
"WC052" : { "name" : "Prince Albert Local Municipality", "layer" : 3, "parent" : "DC5" },
"WC053" : { "name" : "Beaufort West Local Municipality", "layer" : 3, "parent" : "DC5" },
"WCDMA01" : { "name" : "West Coast District Management Area", "layer" : 3, "parent" : "DC1" },
"WCDMA02" : { "name" : "Cape Winelands District Management Area", "layer" : 3, "parent" : "DC2" },
"WCDMA03" : { "name" : "Overberg District Management Area", "layer" : 3, "parent" : "DC3" },
"WCDMA04" : { "name" : "Eden District Management Area", "layer" : 3, "parent" : "DC4" },
"WCDMA05" : { "name" : "Central Karoo District Management Area", "layer" : 3, "parent" : "DC5" }
};
