muniinfo = {
"EC" : { "name" : "Eastern Cape", "layer" : 1, "parent" : null },
"FS" : { "name" : "Free State", "layer" : 1, "parent" : null },
"GT" : { "name" : "Gauteng", "layer" : 1, "parent" : null },
"KZ" : { "name" : "KwaZulu-Natal", "layer" : 1, "parent" : null },
"LP" : { "name" : "Limpopo", "layer" : 1, "parent" : null },
"MP" : { "name" : "Mpumalanga", "layer" : 1, "parent" : null },
"NC" : { "name" : "Northern Cape", "layer" : 1, "parent" : null },
"NW" : { "name" : "North West", "layer" : 1, "parent" : null },
"WC" : { "name" : "Western Cape", "layer" : 1, "parent" : null },
"CPT" : { "name" : "City of Cape Town Metropolitan Municipality", "layer" : 2, "parent" : "WC" },
"DC1" : { "name" : "West Coast District Municipality", "layer" : 2, "parent" : "WC" },
"DC10" : { "name" : "Cacadu District Municipality", "layer" : 2, "parent" : "EC" },
"DC12" : { "name" : "Amatole District Municipality", "layer" : 2, "parent" : "EC" },
"DC13" : { "name" : "Chris Hani District Municipality", "layer" : 2, "parent" : "EC" },
"DC14" : { "name" : "Ukhahlamba District Municipality", "layer" : 2, "parent" : "EC" },
"DC15" : { "name" : "O.R.Tambo District Municipality", "layer" : 2, "parent" : "EC" },
"DC16" : { "name" : "Xhariep District Municipality", "layer" : 2, "parent" : "FS" },
"DC17" : { "name" : "Motheo District Municipality", "layer" : 2, "parent" : "FS" },
"DC18" : { "name" : "Lejweleputswa District Municipality", "layer" : 2, "parent" : "FS" },
"DC19" : { "name" : "Thabo Mofutsanyane District Municipality", "layer" : 2, "parent" : "FS" },
"DC2" : { "name" : "Cape Winelands District Municipality", "layer" : 2, "parent" : "WC" },
"DC20" : { "name" : "Fezile Dabi District Municipality", "layer" : 2, "parent" : "FS" },
"DC21" : { "name" : "Ugu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC22" : { "name" : "UMgungundlovu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC23" : { "name" : "Uthukela District Municipality", "layer" : 2, "parent" : "KZ" },
"DC24" : { "name" : "Umzinyathi District Municipality", "layer" : 2, "parent" : "KZ" },
"DC25" : { "name" : "Amajuba District Municipality", "layer" : 2, "parent" : "KZ" },
"DC26" : { "name" : "Zululand District Municipality", "layer" : 2, "parent" : "KZ" },
"DC27" : { "name" : "Umkhanyakude District Municipality", "layer" : 2, "parent" : "KZ" },
"DC28" : { "name" : "Uthungulu District Municipality", "layer" : 2, "parent" : "KZ" },
"DC29" : { "name" : "iLembe District Municipality", "layer" : 2, "parent" : "KZ" },
"DC3" : { "name" : "Overberg District Municipality", "layer" : 2, "parent" : "WC" },
"DC30" : { "name" : "Gert Sibande District Municipality", "layer" : 2, "parent" : "MP" },
"DC31" : { "name" : "Nkangala District Municipality", "layer" : 2, "parent" : "MP" },
"DC32" : { "name" : "Ehlanzeni District Municipality", "layer" : 2, "parent" : "MP" },
"DC33" : { "name" : "Mopani District Municipality", "layer" : 2, "parent" : "LP" },
"DC34" : { "name" : "Vhembe District Municipality", "layer" : 2, "parent" : "LP" },
"DC35" : { "name" : "Capricorn District Municipality", "layer" : 2, "parent" : "LP" },
"DC36" : { "name" : "Waterberg District Municipality", "layer" : 2, "parent" : "LP" },
"DC37" : { "name" : "Bojanala District Municipality", "layer" : 2, "parent" : "NW" },
"DC38" : { "name" : "Central District Municipality", "layer" : 2, "parent" : "NW" },
"DC39" : { "name" : "Bophirima District Municipality", "layer" : 2, "parent" : "NW" },
"DC4" : { "name" : "Eden District Municipality", "layer" : 2, "parent" : "WC" },
"DC40" : { "name" : "Southern District Municipality", "layer" : 2, "parent" : "NW" },
"DC42" : { "name" : "Sedibeng District Municipality", "layer" : 2, "parent" : "GT" },
"DC43" : { "name" : "Sisonke District Municipality", "layer" : 2, "parent" : "KZ" },
"DC44" : { "name" : "Alfred Nzo District Municipality", "layer" : 2, "parent" : "EC" },
"DC45" : { "name" : "Kgalagadi District Municipality", "layer" : 2, "parent" : "NC" },
"DC46" : { "name" : "Metsweding District Municipality", "layer" : 2, "parent" : "GT" },
"DC47" : { "name" : "Greater Sekhukhune District Municipality", "layer" : 2, "parent" : "LP" },
"DC48" : { "name" : "West Rand District Municipality", "layer" : 2, "parent" : "GT" },
"DC5" : { "name" : "Central Karoo District Municipality", "layer" : 2, "parent" : "WC" },
"DC6" : { "name" : "Namakwa District Municipality", "layer" : 2, "parent" : "NC" },
"DC7" : { "name" : "Pixley ka Seme District Municipality", "layer" : 2, "parent" : "NC" },
"DC8" : { "name" : "Siyanda District Municipality", "layer" : 2, "parent" : "NC" },
"DC9" : { "name" : "Frances Baard District Municipality", "layer" : 2, "parent" : "NC" },
"EKU" : { "name" : "Ekurhuleni Metropolitan Municipality", "layer" : 2, "parent" : "GT" },
"ETH" : { "name" : "eThekwini Metropolitan Municipality", "layer" : 2, "parent" : "KZ" },
"JHB" : { "name" : "City of Johannesburg Metropolitan Municipality", "layer" : 2, "parent" : "GT" },
"NMA" : { "name" : "Nelson Mandela Bay Metropolitan Municipality", "layer" : 2, "parent" : "EC" },
"TSH" : { "name" : "City of Tshwane Metropolitan Municipality", "layer" : 2, "parent" : "GT" }
};
